deploymentMode: Policy
clusterSelectors:
  'hypershift.open-cluster-management.io/hosted-cluster': 'true'
policy:
  destination: "acm-policies"
  complianceType: "musthave"
  extraDependencies:  [{'name': 'rosa-ingress-certificate-check', 'compliance': 'Compliant'}]